insert into properties (
  id,
  smoobu_apartment_id,
  canonical_slug,
  english_slug,
  spanish_slug,
  display_name_en,
  display_name_es,
  guest_capacity,
  thumbnail_url,
  amenities
) values
  (
    'b8a1f2e7-86d3-4c30-8f6a-8046a5f9a111',
    301061,
    'Geco',
    'Geco',
    'GecoES',
    'Casa Geco',
    'Casa Geco',
    5,
    'https://drive.google.com/thumbnail?id=1tYQxiwEXhxhv2r0_mJQhXVAHOMrE0y_2&sz=w1000',
    '[{"code":"bath","label":"Private equipped bathroom"},{"code":"kitchen","label":"Private equipped kitchen"},{"code":"ac","label":"A/C"},{"code":"parking","label":"Private fenced parking"},{"code":"wifi","label":"100Mbps WiFi"},{"code":"pet","label":"Pet friendly"}]'::jsonb
  ),
  (
    'd06f7d50-cbbe-4ec6-954c-3e0f9ac2f2e7',
    301064,
    'Rana',
    'Rana',
    'RanaES',
    'Casa Rana',
    'Casa Rana',
    5,
    'https://drive.google.com/thumbnail?id=1UiGI8gFf6UR5kn8Eo30u457NX8NkP95X&sz=w1000',
    '[{"code":"bath","label":"Private equipped bathroom"},{"code":"kitchen","label":"Private equipped kitchen"},{"code":"ac","label":"A/C"},{"code":"parking","label":"Private fenced parking"},{"code":"wifi","label":"100Mbps WiFi"},{"code":"pet","label":"Pet friendly"}]'::jsonb
  ),
  (
    '64dff2f1-f1cc-4b68-883e-ea3f43efc5a1',
    301055,
    'Tucano',
    'Tucano',
    'TucanoES',
    'Casa Tucano',
    'Casa Tucano',
    5,
    'https://drive.google.com/thumbnail?id=10qvLOMLs4_JsBIF99igVeh4baDR7EB-Q&sz=w1000',
    '[{"code":"bath","label":"Private equipped bathroom"},{"code":"kitchen","label":"Private equipped kitchen"},{"code":"ac","label":"A/C"},{"code":"wifi","label":"100Mbps WiFi"},{"code":"parking","label":"Outside parking"},{"code":"pet","label":"Pet friendly"}]'::jsonb
  ),
  (
    'a75f112f-5aa4-46a7-9f64-1a3b5f30b54c',
    301058,
    'Pappagallo',
    'Pappagallo',
    'PappagalloES',
    'Casa Pappagallo',
    'Casa Pappagallo',
    5,
    'https://drive.google.com/thumbnail?id=1owhxss4VVXLLJAQP1ByDyBMH_NwQsIuY&sz=w1000',
    '[{"code":"bath","label":"Private equipped bathroom"},{"code":"kitchen","label":"Private equipped kitchen"},{"code":"ac","label":"A/C"},{"code":"wifi","label":"100Mbps WiFi"},{"code":"parking","label":"Outside parking"},{"code":"pet","label":"Pet friendly"}]'::jsonb
  ),
  (
    '8d7d5ed0-67a6-44fd-9d57-cb65b104e907',
    1829402,
    'VillaMar',
    'VillaMar',
    'VillaMarES',
    'Villa Mar',
    'Villa Mar',
    2,
    'https://drive.google.com/thumbnail?id=1cl5zzeKajmxVv5_q9cH0cvYQkCRl6kCn&sz=w1000',
    '[{"code":"pool","label":"Private pool"},{"code":"bath","label":"Private equipped bathroom"},{"code":"kitchen","label":"Private equipped kitchen"},{"code":"ac","label":"A/C"},{"code":"parking","label":"Private unfenced parking"},{"code":"wifi","label":"100Mbps WiFi"}]'::jsonb
  ),
  (
    'ec4b9d58-2cf8-4669-88b5-23b9d15c32f6',
    1819085,
    'VillaCoral',
    'VillaCoral',
    'VillaCoralES',
    'Villa Coral',
    'Villa Coral',
    2,
    'https://drive.google.com/thumbnail?id=1frKDGGLk1nJQQaxoxng6TgmUVzxTx08A&sz=w1000',
    '[{"code":"pool","label":"Private pool"},{"code":"bath","label":"Private equipped bathroom"},{"code":"kitchen","label":"Private equipped kitchen"},{"code":"ac","label":"A/C"},{"code":"parking","label":"Private unfenced parking"},{"code":"wifi","label":"100Mbps WiFi"}]'::jsonb
  ),
  (
    '3548c2c7-f7b2-4d5f-8e6f-e01f717f4557',
    1516846,
    'Areka',
    'Areka',
    'ArekaES',
    'Areka',
    'Areka',
    2,
    'https://drive.google.com/thumbnail?id=1iHyOve78WkDNdTcQcUtKkiM8rXx2iRey&sz=w1000',
    '[{"code":"bath","label":"Private equipped bathroom"},{"code":"kitchen","label":"Private equipped kitchen"},{"code":"ac","label":"A/C"},{"code":"wifi","label":"WiFi"},{"code":"parking","label":"Unfenced parking"}]'::jsonb
  ),
  (
    'cba02c24-e7e4-4898-a7d8-c7ae2277a8b1',
    1516849,
    'Plumeria',
    'Plumeria',
    'PlumeriaES',
    'Plumeria',
    'Plumeria',
    2,
    'https://drive.google.com/thumbnail?id=1b2x2aVIjqlSws4KePOS_NVb4NItGsra1&sz=w1000',
    '[{"code":"bath","label":"Private equipped bathroom"},{"code":"kitchen","label":"Private equipped kitchen"},{"code":"ac","label":"A/C"},{"code":"wifi","label":"WiFi"},{"code":"parking","label":"Unfenced parking"}]'::jsonb
  ),
  (
    'c4ff5d9f-ef6d-43f8-8edc-41b0037215de',
    1597723,
    'Giulia',
    'Giulia',
    'GiuliaES',
    'Giulia',
    'Giulia',
    4,
    'https://drive.google.com/thumbnail?id=1e0esqkSBKBdT-F2kLg5PsyF46zEWtWQ8&sz=w1000',
    '[{"code":"bath","label":"Private equipped bathroom"},{"code":"kitchen","label":"Private equipped kitchen"},{"code":"ac","label":"2 A/C"},{"code":"wifi","label":"WiFi"},{"code":"parking","label":"Unfenced parking"}]'::jsonb
  ),
  (
    'bc2470e7-3f18-43e3-91eb-ac3bf3c82ca4',
    2946826,
    'Delfin',
    'Delfin',
    'DelfinES',
    'Delfin',
    'Delfin',
    6,
    'https://drive.google.com/thumbnail?id=1ui0cNzHTb2WM-k59OkwnJXw77m0P7PPW&sz=w1000',
    '[{"code":"bath","label":"2 bathrooms"},{"code":"kitchen","label":"Private equipped kitchen"},{"code":"ac","label":"A/C"},{"code":"wifi","label":"100Mbps WiFi"},{"code":"parking","label":"Private fenced parking"},{"code":"pet","label":"Pet friendly"}]'::jsonb
  )
on conflict (id) do update set
  smoobu_apartment_id = excluded.smoobu_apartment_id,
  canonical_slug = excluded.canonical_slug,
  english_slug = excluded.english_slug,
  spanish_slug = excluded.spanish_slug,
  display_name_en = excluded.display_name_en,
  display_name_es = excluded.display_name_es,
  guest_capacity = excluded.guest_capacity,
  thumbnail_url = excluded.thumbnail_url,
  amenities = excluded.amenities,
  is_active = true,
  updated_at = now();
